-- database/schema.sql
-- (Copie e cole o conteúdo do schema.sql fornecido anteriormente)

CREATE TABLE IF NOT EXISTS cliente (
    IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    CLINOME VARCHAR(255) NOT NULL,
    CLIDOCUMENTO VARCHAR(20) UNIQUE NOT NULL,
    CLIRESPONSAVEL VARCHAR(255),
    CLITELEFONE VARCHAR(20),
    CLICELULAR VARCHAR(20),
    CLIEMAIL VARCHAR(255) UNIQUE NOT NULL,
    CLISENHA VARCHAR(255) NOT NULL,
    CLITIPO ENUM('Pessoa Física', 'Pessoa Jurídica') DEFAULT 'Pessoa Física',
    CLISTATUS ENUM('Ativo', 'Inativo') DEFAULT 'Ativo'
);

CREATE TABLE IF NOT EXISTS tecnico (
    IDTECNICO INT AUTO_INCREMENT PRIMARY KEY,
    TECNOME VARCHAR(255) NOT NULL,
    TECSTATUS ENUM('Ativo', 'Inativo') DEFAULT 'Ativo'
);

CREATE TABLE IF NOT EXISTS produto (
    IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    PRONOME VARCHAR(255) NOT NULL,
    PROVALOR DECIMAL(10, 2) NOT NULL,
    PROESTOQUE INT DEFAULT 0,
    PROMAXDESCONTO DECIMAL(5, 2) DEFAULT 0.00,
    PROSTATUS ENUM('Ativo', 'Inativo') DEFAULT 'Ativo',
    PROTIPO ENUM('Produto', 'Serviço') DEFAULT 'Produto'
);

CREATE TABLE IF NOT EXISTS ordem (
    IDORDEM INT AUTO_INCREMENT PRIMARY KEY,
    ORDDATAABERTURA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ORDIDCLIENTE INT NOT NULL,
    ORDSETOR VARCHAR(100),
    ORDTERMINAL VARCHAR(100),
    ORDNUMEQUIPAMENTO VARCHAR(100),
    ORDRECLAMADO TEXT,
    ORDDIAGNOSTICO TEXT,
    ORDSOLUCAO TEXT,
    ORDDATAAGENDAMENTO DATETIME,
    ORDDATAATENDIMENTO DATETIME,
    ORDVENCIMENTO DATETIME,
    ORDTECNICO INT,
    ORDGARANTIA BOOLEAN DEFAULT FALSE,
    ORDSTATUS ENUM('Aberta', 'Em Atendimento', 'Aguardando Peças', 'Concluída', 'Cancelada') DEFAULT 'Aberta',
    ORDVALORTOTAL DECIMAL(10, 2) DEFAULT 0.00,
    FOREIGN KEY (ORDIDCLIENTE) REFERENCES cliente(IDCLIENTE),
    FOREIGN KEY (ORDTECNICO) REFERENCES tecnico(IDTECNICO)
);

CREATE TABLE IF NOT EXISTS itensOrdem (
    IDITENSORDEM INT AUTO_INCREMENT PRIMARY KEY,
    ITEIDORDEM INT NOT NULL,
    ITEIDPRODUTO INT NOT NULL,
    ITEVALOR DECIMAL(10, 2) NOT NULL,
    ITEQTD INT NOT NULL,
    ITEPERCDESCONTO DECIMAL(5, 2) DEFAULT 0.00,
    ITESUBTOTAL DECIMAL(10, 2) NOT NULL,
    ITESTATUS ENUM('Ativo', 'Cancelado') DEFAULT 'Ativo',
    FOREIGN KEY (ITEIDORDEM) REFERENCES ordem(IDORDEM),
    FOREIGN KEY (ITEIDPRODUTO) REFERENCES produto(IDPRODUTO)
);

CREATE TABLE IF NOT EXISTS usuario (
    IDUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USUNOME VARCHAR(255) NOT NULL,
    USUEMAIL VARCHAR(255) UNIQUE NOT NULL,
    USUSENHA VARCHAR(255) NOT NULL,
    USUTIPO ENUM('Administrador', 'Técnico') NOT NULL,
    USUSTATUS ENUM('Ativo', 'Inativo') DEFAULT 'Ativo',
    USUIDTECNICO INT,
    FOREIGN KEY (USUIDTECNICO) REFERENCES tecnico(IDTECNICO)
);

CREATE TABLE IF NOT EXISTS ticket (
    IDTICKET INT AUTO_INCREMENT PRIMARY KEY,
    TIDCLIENTE INT NOT NULL,
    TIDORDEM INT,
    TASSUNTO VARCHAR(255) NOT NULL,
    TDESCRICAO TEXT NOT NULL,
    TDATAA_BERTURA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TDATAFECHAMENTO DATETIME,
    TSTATUS ENUM('Aberto', 'Em Análise', 'Em Andamento', 'Resolvido', 'Fechado', 'Cancelado') DEFAULT 'Aberto',
    TPRIORIDADE ENUM('Baixa', 'Média', 'Alta', 'Urgente') DEFAULT 'Média',
    TOBSERVACOES TEXT,
    FOREIGN KEY (TIDCLIENTE) REFERENCES cliente(IDCLIENTE),
    FOREIGN KEY (TIDORDEM) REFERENCES ordem(IDORDEM)
);